export {
  getSuppliers,
  getAllSuppliers,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  getSupplierStatistics,
  getPurchaseOrders,
  getPurchaseOrderById,
  createPurchaseOrder,
  updatePurchaseOrder,
  updatePurchaseOrderCosts,
  deletePurchaseOrder,
  getPurchaseOrderStatistics,
  getSupplierProducts,
  addSupplierProduct,
  addSupplierProductsBulk,
  removeSupplierProduct,
} from './suppliers.service';

export type {
  SupplierListItem,
  SupplierContact,
  SupplierDetail,
  SupplierFiltersDto,
  SupplierPagination,
  PaginatedSuppliersDto,
  CreateSupplierDto,
  UpdateSupplierDto,
  SupplierStatistics,
  PurchaseOrderStatus,
  PurchaseOrderItem,
  PurchaseOrder,
  PurchaseOrderFiltersDto,
  PaginatedPurchaseOrdersDto,
  CreatePurchaseOrderItemDto,
  CreatePurchaseOrderDto,
  UpdatePurchaseOrderDto,
  UpdatePurchaseOrderCostsDto,
  PurchaseOrderStatistics,
  SupplierProductItem,
  AddSupplierProductDto,
  BulkAddSupplierProductsDto,
} from './suppliers.types';

export {
  PURCHASE_ORDER_STATUS_LABELS,
  PURCHASE_ORDER_STATUS_COLORS,
  PO_STATUS_TRANSITION_RULES,
  canTransitionPO,
  getAvailablePOTransitions,
  LANDED_COST_FIELDS,
} from './suppliers.types';
